/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-05-15 10:11:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.polarion.portal.jetspeed.gwt.GWTServletProxy;
import com.polarion.platform.i18n.Localization;
import com.polarion.portal.tomcat.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.polarion.portal.tomcat");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.polarion.platform.i18n.Localization");
    _jspx_imports_classes.add("com.polarion.portal.jetspeed.gwt.GWTServletProxy");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
response.setHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
response.setDateHeader("Expires", System.currentTimeMillis() - 10L * 365L * 24L * 60L * 60L * 1000L);

      out.write("\r\n");
      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n");
      out.write("<!DOCTYPE html \r\n");
      out.write("     PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\r\n");
      out.write("    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t    ");
 
	    	String dialogUrl = (String)pageContext.getAttribute("dialogUrl"); 
	    	if(dialogUrl != null) {
	    
	    
      out.write("\r\n");
      out.write("\t    <script src=\"/polarion/oslcDelegatedUI.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("            //<![CDATA[\r\n");
      out.write("                var hash = '/project/");
      out.print( request.getParameter("project") );
      out.write('/');
      out.print( dialogUrl );
      out.write("' + \r\n");
      out.write("                    '&ui_callback=OSLC_delegatedUICallback' + \r\n");
      out.write("                    '&oslc_callback_protocol=' + encodeURIComponent(window.location.hash);\r\n");
      out.write("                window.location.hash = hash;\r\n");
      out.write("            //]]>\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\t\t");
      out.print(com.polarion.portal.tomcat.SupportedBrowsers.getXUACompatibleTag(request));
      out.write("\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"/polarion/ria/images/favicon.ico\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/polarion/gwt/gwt/polarion/polarion.css?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" />\r\n");
      out.write("  \t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\thtml{\r\n");
      out.write("\t\t\t\theight:100%;\r\n");
      out.write("\t\t\t\toverflow:hidden;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\t    font-size:13px;\r\n");
      out.write("            }\r\n");
      out.write("        \tTEXTAREA {\r\n");
      out.write("        \t    font-family:Arial, Helvetica, sans-serif;\r\n");
      out.write("        \t\tresize:none !important;\r\n");
      out.write("        \t    font-size:13px;\r\n");
      out.write("        \t}\r\n");
      out.write("\t\t\tP{\r\n");
      out.write("\t\t\t\tmargin: 0px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tA,TD,DIV,LI,UL,INPUT,BUTTON{\r\n");
      out.write("\t\t\t    font-family:Arial, Helvetica, sans-serif !important;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tINPUT[type=\"file\"]{\r\n");
      out.write("\t\t\t    font-size:11px; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tA:link { text-decoration:none; color:black;}\r\n");
      out.write("\t\t\tA:visited { text-decoration:none; color:black;}\r\n");
      out.write("\t\t\tA:hover { text-decoration:underline; color:black;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t#FIELD_description A:link, #FIELD_comments A:link { \r\n");
      out.write("\t\t\t\tcursor: pointer !important;\r\n");
      out.write("\t\t\t\tcolor: #0277BB !important;\r\n");
      out.write("\t\t\t\ttext-decoration: none !important;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#FIELD_description  A:visited, #FIELD_comments A:visited { \r\n");
      out.write("\t\t\t\tcursor: pointer !important;\r\n");
      out.write("\t\t\t\tcolor: #0277BB !important;\r\n");
      out.write("\t\t\t\ttext-decoration: none !important;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#FIELD_description A:hover, #FIELD_comments A:hover { \r\n");
      out.write("\t\t\t\tcursor: pointer !important;\r\n");
      out.write("\t\t\t\tcolor: #0277BB !important;\r\n");
      out.write("\t\t\t\ttext-decoration: underline !important;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t.polarion-dle-comment-resolved-icon { display:none; }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ta.actionLink {cursor: pointer; text-decoration:underline; color:blue;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.wiki_style p{line-height:1.7em;margin-top:8px;margin-bottom:8px;}\r\n");
      out.write("\t\t\t.wiki_style H1, .wiki_style H2, .wiki_style H3, .wiki_style H4, .wiki_style H5, .wiki_style H6{\r\n");
      out.write("\t\t\tcolor: #0046b0;\r\n");
      out.write("\t\t\tmargin: 0px;\r\n");
      out.write("\t\t\tpadding: 0px;\r\n");
      out.write("\t\t\tpadding-left: 4px;\r\n");
      out.write("\t\t\tpadding-bottom: 0px;\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\tline-height: normal;\r\n");
      out.write("\t\t\tfont-family:Lucida Grande,helvetica,lucida,verdana,sans-serif;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.wiki_style H1{\r\n");
      out.write("\t\t\tfont-size: 18pt;\r\n");
      out.write("\t\t\tborder-bottom: 2px solid #c7c7c7;\r\n");
      out.write("\t\t\tmargin-top: 14px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.wiki_style H2{\r\n");
      out.write("\t\t\tfont-size: 16pt;\r\n");
      out.write("\t\t\tbackground-color:#f2f2f2;\r\n");
      out.write("\t\t\tmargin-top: 24px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.wiki_style H3 {\r\n");
      out.write("\t\t\t\tfont-size: 15pt;\r\n");
      out.write("\t\t\t\tmargin-top: 20px; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.wiki_style H4{\r\n");
      out.write("\t\t\t\tfont-size: 13.5pt;\r\n");
      out.write("\t\t\t\tmargin-top: 20px;}H5{\r\n");
      out.write("\t\t\t\tfont-size: 12pt;\r\n");
      out.write("\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t\tmargin-top: 14px;\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t.wiki_style H6{   font-size: 10pt;   color: black;  margin-top: 14px;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t.wiki_style div.infomessage{text-align: left;width: 95%;margin: 4px 5px;padding: 16px 4px 16px 36px;background: #D8E4F1 url(/polarion/ria/images/msginfo.png) 10px 18px no-repeat;}\r\n");
      out.write("\t\t\t\r\n");
      out.write("            .document_preview {\r\n");
      out.write("                border: 1px solid rgb(204,204,204); \r\n");
      out.write("                background-color: white;\r\n");
      out.write("                font-size: 10pt;\r\n");
      out.write("                line-height:1.5;\r\n");
      out.write("                padding: 40px 40px 40px 40px;\r\n");
      out.write("                \r\n");
      out.write("                font-family: Arial, Verdana, sans-serif;\r\n");
      out.write("                cursor: text;\r\n");
      out.write("                    \r\n");
      out.write("                A:link { text-decoration:none; color:black; }\r\n");
      out.write("                A:visited { text-decoration:none; color:black; }\r\n");
      out.write("                A:hover { text-decoration:underline; color:black; }\r\n");
      out.write("                A.descriptionLink:link { text-decoration:none; color:blue; }\r\n");
      out.write("                A.descriptionLink:visited { text-decoration:none; color:blue; }\r\n");
      out.write("                A.descriptionLink:hover { text-decoration:underline; color:blue; }\r\n");
      out.write("            \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            div.document_preview {\r\n");
      out.write("                width:754px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .document_preview H1, .document_preview H2, .document_preview H3, .document_preview H4, .document_preview H5, .document_preview H6 {\r\n");
      out.write("                    color:#003366;\r\n");
      out.write("                    font-weight:bold;\r\n");
      out.write("                    line-height:1.5;\r\n");
      out.write("                    font-family:Arial, Helvetica, sans-serif;\r\n");
      out.write("                    margin: 0.83em 0 0.41em;\r\n");
      out.write("            }\r\n");
      out.write("                            \r\n");
      out.write("            .document_preview H1 {\r\n");
      out.write("                    border-bottom : 1px solid lightgrey; \r\n");
      out.write("                    font-size : 26pt; \r\n");
      out.write("                    line-height:1.2;\r\n");
      out.write("                    padding-bottom : 5px;\r\n");
      out.write("            }\r\n");
      out.write("                \r\n");
      out.write("            .document_preview H2 {\r\n");
      out.write("                    font-size : 22pt;\r\n");
      out.write("                    line-height:1.2;\r\n");
      out.write("            }\r\n");
      out.write("                            \r\n");
      out.write("            .document_preview H3 {  \r\n");
      out.write("                    font-size : 18pt;\r\n");
      out.write("                    line-height:1.2;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .document_preview H4 {\r\n");
      out.write("                    font-size : 14pt;\r\n");
      out.write("                    line-height:1.2;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .document_preview H5 { \r\n");
      out.write("                    font-size : 12pt;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .document_preview H6 {\r\n");
      out.write("                    font-size : 10pt;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .document_preview P {\r\n");
      out.write("                line-height:1.5;\r\n");
      out.write("            \tmargin: 8px 0px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .document_preview TABLE P {\r\n");
      out.write("                line-height: 14.4px;\r\n");
      out.write("                margin: 0px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.print( com.polarion.core.config.Configuration.getInstance().ui().listStyle().getStyle() );
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t\t</style>\r\n");
      out.write("  \t\t<link rel=\"stylesheet\" href=\"/polarion/ria/font-awesome-4.0.3/css/font-awesome.css\">\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<link rel=\"stylesheet\" href=\"/polarion/ria/codemirror/lib/codemirror.css?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\">\r\n");
      out.write("  \t\t<link rel=\"stylesheet\" href=\"/polarion/ria/codemirror/addon/hint/show-hint.css?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\">\r\n");
      out.write("  \t\t<title></title>\r\n");
      out.write("  \t</head>\r\n");
      out.write("\t<body onbeforeunload=\"try {return handleOnBeforeUnload();}catch(e){}\" style=\"overflow:hidden;height:100%\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t//<![CDATA[\r\n");
      out.write("                onerror = function(errMessage, url, line){\r\n");
      out.write("               \t\tif(url != null && url != \"\"){\r\n");
      out.write("                    \thandleOnError(errMessage + \" \\nline: \" + line + \" \\nurl: \" + url);\r\n");
      out.write("                    }\r\n");
      out.write("                    return true;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                ");

    					boolean isFF4 = com.polarion.portal.tomcat.SupportedBrowsers.isFF4(request);
    					if (isFF4) {
				
      out.write("\r\n");
      out.write("\t\t\t\t\toldalert = alert;\r\n");
      out.write("                \talert = function(message){\r\n");
      out.write("\t                \ttry{\r\n");
      out.write("\t                \t\toldalert(message);\r\n");
      out.write("\t                \t\r\n");
      out.write("\t                \t} catch(e){\r\n");
      out.write("\t                \t\r\n");
      out.write("\t                \t}\r\n");
      out.write("                \t}\r\n");
      out.write("\t\t\t\t");

				    }
				
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\t\t\t//]]>\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"container_div\" style=\"height:100%\" >\r\n");
      out.write("\t\t\t<table style=\"width:100%;height:100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\" valign=\"middle\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/polarion/ria/images/progress.gif\" alt=\"progress\"/>\r\n");
      out.write("\t\t\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.print( Localization.getString("definition.loadingBig") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <iframe src=\"javascript:''\" id=\"__gwt_historyFrame\" tabIndex='-1' style=\"position:absolute;width:0;height:0;border:0\"></iframe>\r\n");
      out.write("\t\t<script src=\"/polarion/gwt/com.polarion.UI/com.polarion.UI.");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getJsTimestamp());
      out.write(".nocache.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/flash_detect.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/liveplan.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/rangy/rangy-core.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/rangy/rangy-selectionsaverestore.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/lib/codemirror.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/mode/xml/xml.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/mode/javascript/javascript.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/mode/css/css.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/mode/htmlmixed/htmlmixed.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/mode/velocity/velocity.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/mode/sql/sql.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/addon/edit/matchbrackets.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/addon/selection/active-line.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/addon/hint/show-hint.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/addon/hint/xml-hint.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/codemirror/addon/edit/closebrackets.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/jquery-1.12.4.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/highcharts.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/highcharts-more.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/highcharts-3d.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/data.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/exporting.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/drilldown.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/funnel.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/heatmap.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/no-data-to-display.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"/polarion/ria/javascript/solid-gauge.js?buildId=");
      out.print(com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId());
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
//add some more code mirror modes 
		for (java.io.File file: ExternalFilesProvider.getAllContributedFiles()){
				String path = "\"codemirror-modes/"+file.getName()+"?buildId="+com.polarion.portal.jetspeed.gwt.GWTServletProxy.getBuildId()+"\"";
				
      out.write("\r\n");
      out.write("\t\t<script src=");
      out.print(path);
      out.write(" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t");
 
		}
		
      out.write(" \r\n");
      out.write("\t\t<iframe src=\"/polarion/ria/prefetch.jsp\" tabIndex='-1' style=\"position:absolute;width:0;height:0;border:0\"></iframe> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//<![CDATA[\r\n");
      out.write("\t\t//]]>\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<script type=\"text/vbscript\"> \r\n");
      out.write("\t\t//<![CDATA[\r\n");
      out.write("\t\tsub openWord(url)\r\n");
      out.write("\t\t  On Error Resume Next\r\n");
      out.write("\t\t\r\n");
      out.write("\t      Set objApp = CreateObject(\"Word.Application\")\r\n");
      out.write("\t      \r\n");
      out.write("\t\t  If Err.number > 0 Then\r\n");
      out.write("         \tMsgBox \"Please allow ActiveX components in your browser to enable this operation.\",vbOKOnly , \"Polarion\"\r\n");
      out.write("        Else\r\n");
      out.write("          \tobjApp.Visible = true\r\n");
      out.write("\t     \tobjApp.Documents.Open url\r\n");
      out.write("         End If\r\n");
      out.write("       \t\r\n");
      out.write("        End sub\r\n");
      out.write("\t\tsub openExcel(url)\r\n");
      out.write("\t\t  On Error Resume Next\r\n");
      out.write("          Set objApp = CreateObject(\"Excel.Application\")\r\n");
      out.write("          If Err.number > 0 Then\r\n");
      out.write("       \t  \tMsgBox \"Please allow ActiveX components in your browser to enable this operation.\",vbOKOnly , \"Polarion\"\r\n");
      out.write("       \t  Else\r\n");
      out.write("       \t  Set objWorkBook = objApp.Workbooks.Open(url)\r\n");
      out.write("    \t  objApp.Visible = true\r\n");
      out.write("\t      End If\r\n");
      out.write("        End sub\r\n");
      out.write("   \t\t//]]>\r\n");
      out.write("   \t\t</script>\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\t");
 if(System.getProperty("google.analytics.number") != null ) {	
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\r\n");
      out.write("document.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("try {\r\n");
      out.write("var pageTracker = _gat._getTracker(\"");
out.print(System.getProperty("google.analytics.number"));
      out.write("\");\r\n");
      out.write("pageTracker._trackPageview();\r\n");
      out.write("} catch(err) {}</script>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
