/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-05-17 11:06:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.include.dialog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.polarion.platform.i18n.Localization;

public final class directoryAddContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.polarion.platform.i18n.Localization");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.polarion.svnwebclient.web.controller.directory.DirectoryAddBean bean = null;
      bean = (org.polarion.svnwebclient.web.controller.directory.DirectoryAddBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        throw new java.lang.InstantiationException("bean bean not found within scope");
      }
      out.write("\r\n");
      out.write("<form name=\"directoryAdd\" method=\"POST\" action=\"");
      out.print(bean.getOkUrl());
      out.write("\" onSubmit=\"if (document.getElementById('directoryname').value <=0 ) {alert('");
      out.print( Localization.getString("svnwebclient.directoryAddContent.alertEnterName") );
      out.write("'); return false;} else {return true;}\" style=\"padding:0;margin:0;\">\r\n");
      out.write("    <table class=\"dialogcontent\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("                <b>");
      out.print( Localization.getString("svnwebclient.directoryAddContent.dirName") );
      out.write("</b>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("                <input type=\"text\" id=\"directoryname\" name=\"directoryname\" style=\"width:100%;margin:0;font-size:11px;\"/>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>    \r\n");
      out.write("        <tr>\r\n");
      out.write("            <td style=\"padding-top:10px;\">\r\n");
      out.write("                <b>");
      out.print( Localization.getString("svnwebclient.revpropscol.comment") );
      out.write("</b>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("                <textarea id=\"comment\" name=\"comment\" rows=\"5\" style=\"width:100%;margin:0;font-size:11px;\">");
      out.print( Localization.getString("svnwebclient.directoryAddContent.defaultComment") );
      out.write("</textarea>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>    \r\n");
      out.write("        <tr>\r\n");
      out.write("            <td width=\"100%\" style=\"padding-top:20px;padding-bottom:0px;\">\r\n");
      out.write("                <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td align=\"left\">\r\n");
      out.write("                            <input type=\"submit\" class=\"button\" value=\"");
      out.print( Localization.getString("svnwebclient.generic.ok") );
      out.write("\"/>                \r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td align=\"left\" style=\"padding-left:10px;\">\r\n");
      out.write("                            <input type=\"button\" class=\"button\" value=\"");
      out.print( Localization.getString("svnwebclient.generic.cancel") );
      out.write("\" onclick=\"javascript:window.location='");
      out.print(bean.getCancelUrl());
      out.write("'\"/>                \r\n");
      out.write("                        </td>      \r\n");
      out.write("                        <td width=\"100%\"/>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </td>    \r\n");
      out.write("        </tr>    \r\n");
      out.write("    </table>\r\n");
      out.write("</form>    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
