/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-05-17 11:07:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.polarion.platform.i18n.Localization;
import org.polarion.svnwebclient.web.model.data.*;

public final class revisionDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.polarion.svnwebclient.web.model.data");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.polarion.platform.i18n.Localization");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      org.polarion.svnwebclient.web.controller.RevisionDetailsBean bean = null;
      bean = (org.polarion.svnwebclient.web.controller.RevisionDetailsBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new org.polarion.svnwebclient.web.controller.RevisionDetailsBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');

    if (bean.execute(request, response)) {
        RevisionDetails content = bean.getRevision();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("jsp.head.title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf( Localization.getString("svnwebclient.revisionDetails.title") ), request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" height=\"100%\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/top.jsp", out, false);
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"padding:0;spacing:0px; padding-left:5px; padding-right:5px; padding-top:2px;\">\r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/infoPanel.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("jsp.infoPanel.info", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("revisionDetailsInfo.jsp", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");

        if (content.isRevisionDecorated()) {

      out.write("            \r\n");
      out.write("            <tr>            \r\n");
      out.write("                <td valign=\"top\" style=\"padding:0;spacing:0px; padding-left:5px; padding-right:5px;\">            \r\n");
      out.write("                    <table class=\"list\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" rules=\"all\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th nowrap=\"true\">\r\n");
      out.write("                                ");
      out.print(content.getDecorationTitle());
      out.write("\r\n");
      out.write("                            </th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                ");
      out.print(content.getDecorationContent());
      out.write("                            \r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>            \r\n");

        }            

      out.write("        \r\n");
      out.write("            <tr>            \r\n");
      out.write("                <td height=\"100%\" valign=\"top\" style=\"padding:0;spacing:0px; padding-left:5px; padding-right:5px;padding-bottom:5px;\">            \r\n");
      out.write("                    <table id=\"table_list_of_revisions\" name=\"table_list_of_revisions\" class=\"list\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" rules=\"all\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th nowrap=\"true\" align=\"left\">\r\n");
      out.write("                                ");
      out.print( Localization.getString("svnwebclient.revisionDetails.changed") );
      out.write("\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <th nowrap=\"true\" align=\"left\">\r\n");
      out.write("                            \t");
      out.print( Localization.getString("svnwebclient.revisionDetails.copyFromPath") );
      out.write("\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <th nowrap=\"true\" align=\"left\">\r\n");
      out.write("                            \t");
      out.print( Localization.getString("svnwebclient.revisionDetails.copyFromRevision") );
      out.write("\r\n");
      out.write("                            </th>\r\n");
      out.write("                        </tr>\r\n");

        for (int i = 0; i < content.getChangedElements().size(); i++) {
            RevisionDetails.Element element = (RevisionDetails.Element) content.getChangedElements().get(i);

      out.write("            \r\n");
      out.write("                        <tr onmouseover=\"selectRow(this)\" onmouseout=\"deselectRow(this)\">\r\n");
      out.write("                            <td width=\"50%\">\r\n");
      out.write("                                <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td class=\"internal\" style=\"padding-right:5px;\">\r\n");
      out.write("                                            <a href=\"");
      out.print(element.getUrl());
      out.write("\">\r\n");
      out.write("                                                <img src=\"");
      out.print(element.getImage());
      out.write("\" />\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td class=\"internal\" width=\"100%\" nowrap=\"true\">\r\n");
      out.write("                                            <a href=\"");
      out.print(element.getUrl());
      out.write("\">\r\n");
      out.write("                                                ");
      out.print(element.getName());
      out.write("    \r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </td>                             \t\t\t\t\t\t                                                                               \r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </td>       \r\n");
      out.write("\t            \t\t\t<td  width=\"50%\" nowrap=\"true\"  align=\"left\">                                                                                \r\n");
      out.write("\t            \t\t\t\t");
      out.print(element.getCopyPath());
      out.write("\r\n");
      out.write("\t                        </td>                             \r\n");
      out.write("\t                        <td nowrap=\"true\" align=\"left\">\r\n");
      out.write("\t                        \t<a href=\"");
      out.print(element.getCopyUrl());
      out.write("\">\t\r\n");
      out.write("\t                         \t\t");
      out.print(element.getCopyRevision());
      out.write("\r\n");
      out.write("\t                         \t</a>\r\n");
      out.write("\t                        </td>                      \r\n");
      out.write("                        </tr>\r\n");
    
        }

      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </body>\r\n");
      out.write("    <script language=\"javascript\">\r\n");
      out.write("        firstsecond('table_list_of_revisions');\r\n");
      out.write("    </script>\r\n");
      out.write("</html>\r\n");

    }

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
